///////////////////////////////////////////////////////////
//  PieceCollection.cs
//  Implementation of the Class PiecesCollection
//  Generated by Enterprise Architect
//  Created on:      08-déc.-2008 15:47:35
//  Original author: Vincent
///////////////////////////////////////////////////////////

#region usings

using System.Collections.Generic;
using ChessLib.Pieces;

#endregion

namespace ChessLib
{
    ///<summary>
    ///
    ///</summary>
    public class PiecesCollection : List<BasePiece>
    {
    }
}