///////////////////////////////////////////////////////////
//  PieceColor.cs
//  Implementation of the Class PieceColor
//  Generated by Enterprise Architect
//  Created on:      08-déc.-2008 15:47:35
//  Original author: Vincent
///////////////////////////////////////////////////////////


///<summary>
///
///</summary>
public enum PieceColor
{
    Black,
    White
}